services:

  db:
    image: postgres:17
    container_name: cocinillas-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - cocinillas_db_network
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocinillas
    environment:
      - ENVIRONMENT_PROFILE=${ENVIRONMENT_PROFILE}
      - DB_START_MODE=${DB_START_MODE}
      - LOAD_INITIAL_DATA=false
      - JAVA_OPTS=${JAVA_OPTS}
      - DB_START_MODE=${DB_START_MODE}
      - EMAIL_PASS=${EMAIL_PASS}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_ACCOUNT=${R2_ACCOUNT}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - DB_USER=srello
      - DB_PASS=doqo3$miT4blet
      - DB_NAME=cocinillas-db
      - TOMCAT_PORT=${TOMCAT_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_TLS_ENABLED=${EMAIL_TLS_ENABLED}
      - EMAIL_TLS_REQUIRED=${EMAIL_TLS_REQUIRED}
      - FRONT_URL=${FRONT_URL}
    networks:
      - cocinillas_db_network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

networks:
  cocinillas_db_network:
    driver: bridge

volumes:
  postgresql:
    name: cocinillas_db_volume
