application:
  title: '@project.name@'
  name: '@project.artifactId@'
  url: 'https://srello.dev'
  version: '@project.version@'

spring:
  application:
    name: cocinillas

  # ---- PROFILE ----
  profiles:
    include:
      - ${ENVIRONMENT_PROFILE:DEV}
      - endpoints
      - swagger
      - security

  # ---- API ----
  mvc:
    servlet:
      path: /api/v1

  # ---- JSON MAPPER ----
#  jackson:
#    default-property-inclusion: non_null

# ---- SERVER ----
server:
  port: ${TOMCAT_PORT:8081}

  # ---- COOKIES ----
  servlet:
    session:
      cookie:
        secure: ${COOKIES_SECURE:true}
        sameSite: ${COOKIES_SAME_SITE:strict}

security:
  cors: ${CORS_ORIGIN:*}
# ---- LOGGING ----
#logging:
#  level:
#    root: ${LOGGING_ROOT:INFO}
#    org.springframework.web: ${LOGGING_SPRING_WEB:INFO}
#    org.springframework.boot.autoconfigure.logging: ${LOGGING_SPRING_BOOT:INFO}
#    app.ipreach.backend: ${LOGGING_API:INFO}
#    org.hibernate.SQL: ${LOGGING_HIBERNATE:ERROR}
#    org.hibernate.type.descriptor.sql: ${LOGGING_HIBERNATE:ERROR}
#    org.hibernate.orm.jdbc.bind: ${LOGGING_HIBERNATE:ERROR}

#---- EMAIL ----
email:
  app-direction: "noreply@cocinillas.app"
  host: ${EMAIL_HOST:smtp.gmail.com}
  port: ${EMAIL_SMTP_PORT:587}
  username: ${EMAIL_USER:noreply.cocinillas.app@gmail.com}
  password: ${EMAIL_PASS}
  properties:
    smtp:
      auth: true
      connectiontimeout: 20000
      starttls:
        enable: ${EMAIL_TLS_ENABLED:false}
        required: ${EMAIL_TLS_REQUIRED:false}
      timeout: 5000
      writetimeout: 5000

front:
  url: ${FRONT_URL:http://localhost:5173}

r2:
  accountId: ${R2_ACCOUNT}
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET:cocinillas-app}
  presigned-url-duration: ${R2_DURATION:5}
  region: ${R2_REGION:weur}
  cache:
